#!/usr/bin/env python3
"""Demo CGI script: echoes the request back as an HTML page."""

import os
import sys
import html

method = os.environ.get("REQUEST_METHOD", "GET")
query = os.environ.get("QUERY_STRING", "")
length = int(os.environ.get("CONTENT_LENGTH", "0") or "0")
body = sys.stdin.read(length) if length > 0 else ""
cookie = os.environ.get("HTTP_COOKIE", "")

name = "world"
if query:
    params = dict(p.split("=", 1) for p in query.split("&") if "=" in p)
    name = params.get("name", "world")

rows = [
    ("method", method),
    ("path", os.environ.get("SCRIPT_NAME", "")),
    ("query", query),
    ("body", body if body else "(empty)"),
    ("cookie", cookie if cookie else "(none)"),
]

out = []
out.append("Content-Type: text/html; charset=utf-8")
out.append("")
out.append("<h1>Hello, {}!</h1>".format(html.escape(name)))
out.append("<p>This page was generated by a <strong>python CGI</strong>.</p>")
out.append("<table border='0'>")
for key, value in rows:
    out.append("<tr><td><code>{}</code></td><td>{}</td></tr>".format(
        key, html.escape(str(value))))
out.append("</table>")
out.append("<p><a href='/cgi-bin/hello.py?name=42student'>say hello to a student</a></p>")
sys.stdout.write("\n".join(out))
